GET http://localhost:4000/api/users/1


POST http://localhost:4000/api/users
Content-Type: application/json

{
    "firstName":"First",
    "lastName":"Last",
    "email":"mail1@mail.com",
    "tel":"+380987654325"
}

GET http://localhost:4000/api/users

POST http://localhost:4000/api/users
Content-Type: application/json

{
    "firstName":"First",
    "lastName":"Last",
    "email":"mail1@mail.com",
    "tel":"+3809871234567890"
}

GET http://localhost:4000/api/users?page=2&results=5